
-- Status
INSERT INTO T_SMARTMOTTU_STATUS_MOTO (id_status, status, data)
VALUES (SQ_T_SMARTMOTTU_STATUS_MOTO.NEXTVAL, 'ATIVO', SYSDATE);

INSERT INTO T_SMARTMOTTU_STATUS_MOTO (id_status, status, data)
VALUES (SQ_T_SMARTMOTTU_STATUS_MOTO.NEXTVAL, 'INATIVO', SYSDATE);

INSERT INTO T_SMARTMOTTU_STATUS_MOTO (id_status, status, data)
VALUES (SQ_T_SMARTMOTTU_STATUS_MOTO.NEXTVAL, 'BLOQUEADO', SYSDATE);

INSERT INTO T_SMARTMOTTU_STATUS_MOTO (id_status, status, data)
VALUES (SQ_T_SMARTMOTTU_STATUS_MOTO.NEXTVAL, 'CANCELADO', SYSDATE);

INSERT INTO T_SMARTMOTTU_STATUS_MOTO (id_status, status, data)
VALUES (SQ_T_SMARTMOTTU_STATUS_MOTO.NEXTVAL, 'MANUTENCAO', SYSDATE);

-- Tipo Moto
INSERT INTO T_SMARTMOTTU_TIPO_MOTO (id_tipo, nm_tipo)
VALUES (SQ_T_SMARTMOTTU_TIPO_MOTO.NEXTVAL,'MOTTU_SPORT_110I');
COMMIT;

INSERT INTO T_SMARTMOTTU_TIPO_MOTO (id_tipo, nm_tipo)
VALUES (SQ_T_SMARTMOTTU_TIPO_MOTO.NEXTVAL,'MOTTU_SPORT_ESD_2025');


-- Adicionando Dados no Usuario
INSERT INTO T_SMARTMOTTU_USUARIO (id_usuario, nome, email, senha)
VALUES (SQ_T_SMARTMOTTU_USUARIO.NEXTVAL, 'Sofia Petruk', 'sofia.petruk@fiap.com.br', '123456');

INSERT INTO T_SMARTMOTTU_USUARIO (id_usuario, nome, email, senha)
VALUES (SQ_T_SMARTMOTTU_USUARIO.NEXTVAL, 'João Silva', 'joao.silva@exemplo.com', 'abcdef');

-- Adicionando Dados na Moto
INSERT INTO T_SMARTMOTTU_MOTO (id_moto, nm_chassi, placa, unidade, fk_id_status, fk_id_tipo)
VALUES (SQ_T_SMARTMOTTU_MOTO.NEXTVAL, '9BWZZZ377VT004255', 'ABC1234', 'Unidade São Paulo', 1, 1);

INSERT INTO T_SMARTMOTTU_MOTO (id_moto, nm_chassi, placa, unidade, fk_id_status, fk_id_tipo)
VALUES (SQ_T_SMARTMOTTU_MOTO.NEXTVAL, '9BWZZZ377VT004252', 'XYZ5678', 'Unidade Rio de Janeiro', 2, 2);