CREATE TABLE T_SMARTMOTTU_ALUGUEL (
    id_aluguel NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    fk_usuario_id NUMBER NOT NULL,
    fk_moto_id NUMBER NOT NULL,

    data_inicio DATE NOT NULL,
    data_fim DATE,
    valor_total NUMBER(10,2),

    status VARCHAR2(20) NOT NULL,

    CONSTRAINT fk_aluguel_usuario FOREIGN KEY (fk_usuario_id)
        REFERENCES T_SMARTMOTTU_USUARIO (id_usuario),
    CONSTRAINT fk_aluguel_moto FOREIGN KEY (fk_moto_id)
        REFERENCES T_SMARTMOTTU_MOTO (id_moto)
);